from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Iterable, Sequence

from .models import SkillPlan

if TYPE_CHECKING:  # pragma: no cover - import cycle guard for type checkers only
    from .ontology import Derivation, Ontology


#: Microseconds, not seconds. A run costs about 0.13s, so two consecutive
#: invocations into one directory share a second, and the exclusive create
#: below would refuse the second one as a routine outcome -- which trains a
#: caller to ignore the warning that exists for the symlink case.
GRAPH_FILENAME_FORMAT = "agent-workflows-%Y%m%dT%H%M%S%fZ.dot"
#: What the graph label says when no --ontology file was supplied.
BUNDLED_SOURCE = "bundled default"

# What this renderer may draw: values the run produced -- the ontology rows it
# was evaluated against, the derivations `derive()` returned, and the plan
# `select_plan()` returned, including each skill's own `reason` string.
#
# What it may not draw: anything it would have to recompute. `needs_plan` and
# `needs_broad_tests` live only inside selector.RULES and are never returned,
# so a node for either would be a second copy of the rules in a renderer with
# nothing keeping the two in sync. The same goes for any property -> skill
# edge: which rule fired for which property is exactly the knowledge this
# module does not hold. Using `reason` as the label on the request -> skill
# edge says why a skill was selected without the renderer knowing one rule.
#
# The test of the line: if drawing something needs a fact outside these three
# arguments, it does not belong here.


def graph_filename(moment: datetime) -> str:
    """Name the graph for one instant, sortably and legally on every platform.

    Basic ISO 8601 rather than the extended form `datetime.isoformat` emits:
    `:` is illegal in a Windows filename, and the whole point of the name is
    that a caller can find the file afterwards. Lexicographic order is
    chronological order because every field is fixed width.

    Converted rather than assumed: the format ends in a literal `Z`, so a
    caller handing this a local or otherwise offset datetime would otherwise
    get a name that says UTC and is not. A naive datetime is read as local
    time, which is what `astimezone` already means by it.
    """

    return moment.astimezone(UTC).strftime(GRAPH_FILENAME_FORMAT)


def build_dot(
    ontology: "Ontology",
    plan: SkillPlan,
    derivations: "Sequence[Derivation]" = (),
    *,
    moment: datetime,
    source: str = BUNDLED_SOURCE,
) -> str:
    """Render one run -- the active TBox and the selection it produced -- as DOT.

    ``plan`` is required rather than optional because a graph is always a
    run's graph. A TBox-only rendering would be a different artifact under the
    same filename, and the caller that has no plan is the one that must not
    write a file at all.
    """

    lines: list[str] = []
    emit = lines.append

    emit("// Generated by agent-workflows-harness. Render with:")
    emit("//   dot -Tsvg <this file> -o run.svg")
    emit("digraph agent_workflows_run {")
    emit("  rankdir=TB;")
    emit("  compound=true;")
    emit("  labelloc=\"t\";")
    emit(
        "  label=\"agent-workflows harness run  ·  {}  ·  ontology: {}\";".format(
            _escape(moment.isoformat()), _escape(source)
        )
    )
    emit("  fontname=\"Helvetica\";")
    emit("  node [fontname=\"Helvetica\", fontsize=11, shape=box, style=\"rounded,filled\","
         " fillcolor=\"white\", color=\"#555555\"];")
    emit("  edge [fontname=\"Helvetica\", fontsize=9, color=\"#666666\"];")

    derived_edges = _derived_edges(ontology, derivations)
    held = set(plan.request.properties)
    selected = {skill.skill_id for skill in plan.selected}
    blocked = {skill.skill_id for skill in plan.blocked}

    individuals = sorted({left for left, _ in ontology.surface_class})
    classes = sorted(
        {term for pair in ontology.sub_class_of for term in pair}
        | {right for _, right in ontology.skill_class}
        | {right for _, right in ontology.surface_class}
    )
    scopes = sorted({left for left, _ in ontology.scope_property})
    properties = sorted(
        {right for _, right in ontology.property_of_class}
        | {right for _, right in ontology.scope_property}
        | held
        | {item.request_property for item in derivations}
    )
    # A selected skill absent from a custom TBox's skill_class still gets a
    # node: the plan is what the graph is about, and dropping it would draw a
    # run that did not happen.
    skills = sorted({left for left, _ in ontology.skill_class} | selected | blocked)

    _cluster(
        emit,
        "individuals",
        "individuals  ·  --touches",
        "#8ab4d8",
        "#f4f9fd",
        [(_node("ind", term), {"label": term, "fillcolor": "#e3f0fb"}) for term in individuals],
    )
    _cluster(
        emit,
        "classes",
        "classes  ·  sub_class_of",
        "#9c8ab8",
        "#f8f5fc",
        [(_node("cls", term), {"label": term, "fillcolor": "#ece4f6"}) for term in classes],
    )
    _cluster(
        emit,
        "scopes",
        "scopes  ·  --scope",
        "#8ab4d8",
        "#f4f9fd",
        [(_node("scope", term), {"label": term, "fillcolor": "#e3f0fb"}) for term in scopes],
    )
    _cluster(
        emit,
        "properties",
        "request properties",
        "#6aa84f",
        "#f3f9f0",
        [
            (
                _node("prop", term),
                {
                    "label": term,
                    "shape": "ellipse",
                    # A property the request holds is filled; one the TBox
                    # merely declares is outlined. `held` is plan.request
                    # .properties -- a value the plan carries, so this states
                    # the outcome without restating the normalization that
                    # produced it.
                    "fillcolor": "#dff0d5" if term in held else "white",
                },
            )
            for term in properties
        ],
    )
    _cluster(
        emit,
        "skills",
        "skills  ·  selected_skill / blocked_skill",
        "#555555",
        "#fafafa",
        [(_node("skill", term), _skill_attributes(term, plan)) for term in skills],
    )

    # Ordering the selected skills by execution order costs one invisible
    # chain and is the difference between a plan a reader can follow and a
    # bag of boxes. Blocked skills are deliberately left out of it: they never
    # run, so placing them in the sequence would assert a step that does not.
    ordered = [_node("skill", skill.skill_id) for skill in plan.selected]
    if len(ordered) > 1:
        emit("  // execution order")
        emit("  " + " -> ".join(ordered) + " [style=invis];")

    emit("  // the request this graph is about")
    emit(
        "  {} [label=\"{}\\n{}\", shape=note, fillcolor=\"#fff6f6\", color=\"#b4463f\"];".format(
            _REQUEST, _escape(plan.request.request_id), _escape(plan.request.request_type)
        )
    )

    _relation(emit, "surface_class", ontology.surface_class, "ind", "cls", derived_edges)
    _relation(
        emit,
        "sub_class_of",
        ontology.sub_class_of,
        "cls",
        "cls",
        derived_edges,
        label="⊑",
        style="dashed",
        color="#3f6fb0",
    )
    _relation(
        emit,
        "property_of_class",
        ontology.property_of_class,
        "cls",
        "prop",
        derived_edges,
        color="#4e7a3a",
    )
    _relation(emit, "scope_property", ontology.scope_property, "scope", "prop", derived_edges)
    _relation(
        emit,
        "skill_class",
        ontology.skill_class,
        "skill",
        "cls",
        derived_edges,
        style="dotted",
        color="#b3a5c9",
    )

    # Derived edges with no row behind them. `docs_only` is the case that
    # exists today: derive() returns it with the path (DocSurface, docs_only),
    # and no property_of_class row carries it, because it is inferred from the
    # absence of a non-doc touch rather than from a class membership.
    drawn = _relation_pairs(ontology)
    orphans = sorted(derived_edges - drawn)
    if orphans:
        emit("  // derived, with no TBox row behind them")
        for src, dst in orphans:
            emit(_edge(src, dst, label="derived", **_DERIVED))

    emit("  // what the request holds")
    for prop in sorted(held):
        emit(_edge(_REQUEST, _node("prop", prop), label="property", color="#4e7a3a"))

    emit("  // what the selector decided, labelled with its own reason")
    for skill in plan.selected:
        emit(
            _edge(
                _REQUEST,
                _node("skill", skill.skill_id),
                label=f"{skill.order} · {skill.reason}",
                color="#a4661d",
                penwidth="1.6",
            )
        )
    for skill in plan.blocked:
        emit(
            _edge(
                _REQUEST,
                _node("skill", skill.skill_id),
                label=skill.reason,
                color="#b4463f",
                style="dotted",
            )
        )

    emit("}")
    return "\n".join(lines) + "\n"


def write_graph(
    directory: str | Path,
    ontology: "Ontology",
    plan: SkillPlan,
    derivations: "Sequence[Derivation]" = (),
    *,
    moment: datetime | None = None,
    source: str = BUNDLED_SOURCE,
) -> Path:
    """Write one run's graph into ``directory`` and return the path written.

    The directory is the caller's to validate: the CLI rejects a missing or
    empty one as bad input before any run work happens, and duplicating that
    check here would give the rule two homes that can drift apart. What this
    does refuse is clobbering.

    Exclusive create, not truncate. The default directory is the world-writable
    system temp and the filename is fully predictable, so a plain "w" is a
    textbook predictable-name symlink target; "x" is O_CREAT|O_EXCL, which
    fails on an existing symlink rather than following it. With microsecond
    timestamps a collision is an anomaly worth reporting rather than the normal
    outcome of running twice.

    LF on every platform, named rather than inherited. `build_dot` joins with
    LF and this module sorts every relation so that two runs render the same
    bytes; a text-mode write that does not name a newline turns each one into
    CRLF on Windows, which ends that promise at the file boundary and leaves
    the same graph on two platforms as two different byte sequences. graphviz
    reads either, so this is for the caller diffing two graphs rather than for
    the parser.
    """

    moment = moment if moment is not None else datetime.now(UTC)
    target = Path(directory) / graph_filename(moment)
    with target.open("x", encoding="utf-8", newline="\n") as handle:
        handle.write(build_dot(ontology, plan, derivations, moment=moment, source=source))
    return target


_REQUEST = '"req"'
# One dict so a derived edge cannot be styled two ways in two places.
_DERIVED = {"color": "#b34700", "penwidth": "2.2"}


def _escape(text: str) -> str:
    """Escape a term for a DOT double-quoted string.

    Every id and label is quoted rather than emitted bare: `run-broad-tests`
    is not a bare DOT identifier, and a term is free to collide with a DOT
    keyword. Backslash first, or the quote's own escape would be re-escaped.
    """

    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _node(kind: str, term: str) -> str:
    """Namespace a node id by what the term is.

    Nothing forbids a TBox declaring an individual named `trivial`, which is
    also a request property; bare ids would merge the two into one node and
    draw an edge that no row asserts. `:` cannot occur in a term
    (ontology._TERM_PATTERN), so the prefix can never be part of the name.
    """

    return f'"{kind}:{_escape(term)}"'


def _attributes(attrs: dict[str, str]) -> str:
    return ", ".join(f'{key}="{_escape(value)}"' for key, value in attrs.items())


def _edge(src: str, dst: str, **attrs: str) -> str:
    return f"  {src} -> {dst} [{_attributes(attrs)}];"


def _cluster(
    emit,
    name: str,
    label: str,
    color: str,
    background: str,
    nodes: Sequence[tuple[str, dict[str, str]]],
) -> None:
    if not nodes:
        # An empty relation draws an empty labelled box, which asserts a
        # category the TBox does not have.
        return
    emit(f"  subgraph cluster_{name} {{")
    emit(f'    label="{_escape(label)}";')
    emit(f'    style="rounded"; color="{color}"; bgcolor="{background}";')
    for node, attrs in nodes:
        emit(f"    {node} [{_attributes(attrs)}];")
    emit("  }")


def _skill_attributes(skill_id: str, plan: SkillPlan) -> dict[str, str]:
    for skill in plan.selected:
        if skill.skill_id == skill_id:
            return {"label": f"{skill.order} · {skill_id}", "fillcolor": "#fbe7c8"}
    for skill in plan.blocked:
        if skill.skill_id == skill_id:
            return {"label": f"{skill_id} (blocked)", "fillcolor": "#fff6f6", "style": "rounded,filled,dashed"}
    return {"label": skill_id, "fillcolor": "#eeeeee"}


def _relation(
    emit,
    name: str,
    rows: Iterable[tuple[str, str]],
    left_kind: str,
    right_kind: str,
    derived_edges: set[tuple[str, str]],
    *,
    label: str | None = None,
    style: str | None = None,
    color: str | None = None,
) -> None:
    rows = sorted(rows)
    if not rows:
        return
    emit(f"  // {name}")
    for left, right in rows:
        src, dst = _node(left_kind, left), _node(right_kind, right)
        attrs: dict[str, str] = {"label": label if label is not None else name}
        if style is not None:
            attrs["style"] = style
        if color is not None:
            attrs["color"] = color
        if (src, dst) in derived_edges:
            # The run travelled this row. Restyling it in place, rather than
            # drawing a second edge beside it, is what makes the derivation
            # legible as a path through the TBox instead of a parallel copy.
            attrs.update(_DERIVED)
        emit(_edge(src, dst, **attrs))


def _relation_pairs(ontology: "Ontology") -> set[tuple[str, str]]:
    """Every edge the TBox relations already draw, as node-id pairs."""

    pairs = {(_node("ind", left), _node("cls", right)) for left, right in ontology.surface_class}
    pairs |= {(_node("cls", left), _node("cls", right)) for left, right in ontology.sub_class_of}
    pairs |= {
        (_node("cls", left), _node("prop", right)) for left, right in ontology.property_of_class
    }
    pairs |= {
        (_node("scope", left), _node("prop", right)) for left, right in ontology.scope_property
    }
    pairs |= {(_node("skill", left), _node("cls", right)) for left, right in ontology.skill_class}
    return pairs


def _derived_edges(
    ontology: "Ontology", derivations: "Sequence[Derivation]"
) -> set[tuple[str, str]]:
    """The edges this run actually travelled, as node-id pairs."""

    edges: set[tuple[str, str]] = set()
    for item in derivations:
        nodes = _path_nodes(ontology, item)
        edges.update(zip(nodes, nodes[1:]))
    return edges


def _path_nodes(ontology: "Ontology", item: "Derivation") -> list[str]:
    """Resolve one derivation's path to node ids, by shape.

    A term alone does not say what kind of node it is -- a TBox may declare a
    class named like a request property -- so nothing here decides a kind by
    comparing a term to `request_property`. derive() builds exactly three
    shapes: a scope path is (scope, property), a surface path runs
    individual -> class -> ... -> class and leaves the property implicit, and
    the docs_only path is (DocSurface, docs_only).

    The last two are told apart by what the TBox declares rather than by what
    the term is called: a surface path ends on a declared class, and the
    docs_only property is not one. That is also what keeps every id emitted
    here an id the graph declares, including for the TBox pathological enough
    to declare an individual named after the doc-surface class: that path
    resolves to (individual, property), which mis-styles the one edge it draws
    and leaves both of its endpoints declared.
    """

    individuals = ontology.individuals()
    classes = ontology.classes()
    length = len(item.path)
    if item.source.startswith("scope(req,"):
        kinds = ["scope"] + ["prop"] * (length - 1)
    else:
        kinds = (
            ["ind" if item.path[0] in individuals else "cls"]
            + ["cls"] * (length - 2)
            + ["cls" if item.path[-1] in classes else "prop"]
        )

    nodes = [_node(kind, term) for kind, term in zip(kinds, item.path)]
    # A surface path stops at the class that carries the property, so the
    # property_of_class edge it then travelled has to be appended; the other
    # two shapes already end on the property.
    tail = _node("prop", item.request_property)
    if nodes and nodes[-1] != tail:
        nodes.append(tail)
    return nodes
